services:
  agentic-ti-os:
    container_name: agentic-core
    build:
      context: ../..
      dockerfile: runtime/docker/Dockerfile
    env_file: .env
    volumes:
      - ../../src:/app/src
    stdin_open: true
    tty: true
